"""
This type stub file was generated by pyright.
"""

import sys
from debugpy.public_api import *
from debugpy.public_api import __version__

"""An implementation of the Debug Adapter Protocol (DAP) for Python.

https://microsoft.github.io/debug-adapter-protocol/
"""
__all__ = ["__version__", "breakpoint", "configure", "connect", "debug_this_thread", "is_client_connected", "listen", "log_to", "trace_this_thread", "wait_for_client"]
