"""
This type stub file was generated by pyright.
"""

from ._presets import StereoMatching
from ._augment import SimpleCopyPaste
from ._geometry import FixedSizeCrop
from ._misc import PermuteDimensions, TransposeDimensions
from ._type_conversion import LabelToOneHot

