"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Union
from torchvision.transforms.v2 import InterpolationMode, Transform

class SimpleCopyPaste(Transform):
    def __init__(self, blending: bool = ..., resize_interpolation: Union[int, InterpolationMode] = ..., antialias: Optional[bool] = ...) -> None:
        ...
    
    def forward(self, *inputs: Any) -> Any:
        ...
    


