"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Sequence, Type, Union
from torchvision.transforms.v2 import Transform
from torchvision.transforms.v2._utils import _FillType

class FixedSizeCrop(Transform):
    def __init__(self, size: Union[int, Sequence[int]], fill: Union[_FillType, Dict[Union[Type, str], _FillType]] = ..., padding_mode: str = ...) -> None:
        ...
    
    def check_inputs(self, flat_inputs: List[Any]) -> None:
        ...
    
    def make_params(self, flat_inputs: List[Any]) -> Dict[str, Any]:
        ...
    
    def transform(self, inpt: Any, params: Dict[str, Any]) -> Any:
        ...
    


