"""
This type stub file was generated by pyright.
"""

import torch
from typing import Any, Dict, Optional, Sequence, Tuple, Type, TypeVar, Union
from torchvision.transforms.v2 import Transform

T = TypeVar("T")
class PermuteDimensions(Transform):
    _transformed_types = ...
    def __init__(self, dims: Union[Sequence[int], Dict[Type, Optional[Sequence[int]]]]) -> None:
        ...
    
    def transform(self, inpt: Any, params: Dict[str, Any]) -> torch.Tensor:
        ...
    


class TransposeDimensions(Transform):
    _transformed_types = ...
    def __init__(self, dims: Union[Tuple[int, int], Dict[Type, Optional[Tuple[int, int]]]]) -> None:
        ...
    
    def transform(self, inpt: Any, params: Dict[str, Any]) -> torch.Tensor:
        ...
    


