"""
This type stub file was generated by pyright.
"""

import torch
from typing import Optional, Tuple, Union
from torch import Tensor
from torchvision.transforms.v2 import InterpolationMode

"""
This file is part of the private API. Please do not use directly these classes as they will be modified on
future versions without warning. The classes should be accessed only via the transforms argument of Weights.
"""
__all__ = ["StereoMatching"]
class StereoMatching(torch.nn.Module):
    def __init__(self, *, use_gray_scale: bool = ..., resize_size: Optional[Tuple[int, ...]], mean: Tuple[float, ...] = ..., std: Tuple[float, ...] = ..., interpolation: Union[InterpolationMode, int] = ...) -> None:
        ...
    
    def forward(self, left_image: Tensor, right_image: Tensor) -> Tuple[Tensor, Tensor]:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def describe(self) -> str:
        ...
    


