"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict
from torchvision.prototype import tv_tensors as proto_tv_tensors
from torchvision.transforms.v2 import Transform

class LabelToOneHot(Transform):
    _transformed_types = ...
    def __init__(self, num_categories: int = ...) -> None:
        ...
    
    def transform(self, inpt: proto_tv_tensors.Label, params: Dict[str, Any]) -> proto_tv_tensors.OneHotLabel:
        ...
    
    def extra_repr(self) -> str:
        ...
    


