"""
This type stub file was generated by pyright.
"""

def launch_request(request): # -> dict[Any, Any]:
    ...

def terminate_request(request): # -> None:
    ...

def disconnect(): # -> None:
    ...

