"""
This type stub file was generated by pyright.
"""

class CaptureOutput:
    """Captures output from the specified file descriptor, and tees it into another
    file descriptor while generating DAP "output" events for it.
    """
    instances = ...
    def __init__(self, whose, category, fd, stream) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    


def wait_for_remaining_output(): # -> None:
    """Waits for all remaining output to be captured and propagated."""
    ...

