"""
This type stub file was generated by pyright.
"""

import os
import typing

if typing.TYPE_CHECKING:
    __all__: list[str]
    ...
__all__ = []
PROCESS_SPAWN_TIMEOUT = ...
PROCESS_EXIT_TIMEOUT = ...
