"""
This type stub file was generated by pyright.
"""

def create_server(host, port=..., backlog=..., timeout=...): # -> socket:
    """Return a local server socket listening on the given port."""
    ...

def create_client(): # -> socket:
    """Return a client socket that may be connected to a remote address."""
    ...

def shut_down(sock, how=...): # -> None:
    """Shut down the given socket."""
    ...

def close_socket(sock): # -> None:
    """Shutdown and close the socket."""
    ...

def serve(name, handler, host, port=..., backlog=..., timeout=...): # -> socket:
    """Accepts TCP connections on the specified host and port, and invokes the
    provided handler function for every new connection.

    Returns the created server socket.
    """
    ...

