"""
This type stub file was generated by pyright.
"""

"""Provides monotonic timestamps with a resetable zero.
"""
__all__ = ["current", "reset"]
def current(): # -> float:
    ...

def reset(): # -> None:
    ...

