"""
This type stub file was generated by pyright.
"""

import numpy as np
import PIL.Image
import torch
from typing import Any, Dict, Optional, Union
from torchvision import tv_tensors
from torchvision.transforms.v2 import Transform

class PILToTensor(Transform):
    """Convert a PIL Image to a tensor of the same type - this does not scale values.

    This transform does not support torchscript.

    Converts a PIL Image (H x W x C) to a Tensor of shape (C x H x W).
    """
    _transformed_types = ...
    def transform(self, inpt: PIL.Image.Image, params: Dict[str, Any]) -> torch.Tensor:
        ...
    


class ToImage(Transform):
    """Convert a tensor, ndarray, or PIL Image to :class:`~torchvision.tv_tensors.Image`
    ; this does not scale values.

    This transform does not support torchscript.
    """
    _transformed_types = ...
    def transform(self, inpt: Union[torch.Tensor, PIL.Image.Image, np.ndarray], params: Dict[str, Any]) -> tv_tensors.Image:
        ...
    


class ToPILImage(Transform):
    """Convert a tensor or an ndarray to PIL Image

    This transform does not support torchscript.

    Converts a torch.*Tensor of shape C x H x W or a numpy ndarray of shape
    H x W x C to a PIL Image while adjusting the value range depending on the ``mode``.

    Args:
        mode (`PIL.Image mode`_): color space and pixel depth of input data (optional).
            If ``mode`` is ``None`` (default) there are some assumptions made about the input data:

            - If the input has 4 channels, the ``mode`` is assumed to be ``RGBA``.
            - If the input has 3 channels, the ``mode`` is assumed to be ``RGB``.
            - If the input has 2 channels, the ``mode`` is assumed to be ``LA``.
            - If the input has 1 channel, the ``mode`` is determined by the data type (i.e ``int``, ``float``,
              ``short``).

    .. _PIL.Image mode: https://pillow.readthedocs.io/en/latest/handbook/concepts.html#concept-modes
    """
    _transformed_types = ...
    def __init__(self, mode: Optional[str] = ...) -> None:
        ...
    
    def transform(self, inpt: Union[torch.Tensor, PIL.Image.Image, np.ndarray], params: Dict[str, Any]) -> PIL.Image.Image:
        ...
    


class ToPureTensor(Transform):
    """Convert all TVTensors to pure tensors, removing associated metadata (if any).

    This doesn't scale or change the values, only the type.
    """
    _transformed_types = ...
    def transform(self, inpt: Any, params: Dict[str, Any]) -> torch.Tensor:
        ...
    


