"""
This type stub file was generated by pyright.
"""

import torch
from typing import Any, Optional, Sequence, Type, TypeVar, Union
from torchvision.tv_tensors._tv_tensor import TVTensor

L = TypeVar("L", bound="_LabelBase")
class _LabelBase(TVTensor):
    categories: Optional[Sequence[str]]
    def __new__(cls: Type[L], data: Any, *, categories: Optional[Sequence[str]] = ..., dtype: Optional[torch.dtype] = ..., device: Optional[Union[torch.device, str, int]] = ..., requires_grad: Optional[bool] = ...) -> L:
        ...
    
    @classmethod
    def from_category(cls: Type[L], category: str, *, categories: Sequence[str], **kwargs: Any) -> L:
        ...
    


class Label(_LabelBase):
    def to_categories(self) -> Any:
        ...
    


class OneHotLabel(_LabelBase):
    def __new__(cls, data: Any, *, categories: Optional[Sequence[str]] = ..., dtype: Optional[torch.dtype] = ..., device: Optional[Union[torch.device, str, int]] = ..., requires_grad: bool = ...) -> OneHotLabel:
        ...
    


